export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import { useRouter } from "next/navigation";
import { getServerSession } from "next-auth";
import { useSession } from "next-auth/react";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
